"""Route contracts for Stage 2 RAG namespace planning."""

from __future__ import annotations

from rag.contracts import RAG_API_ROUTE_PREFIX, RAG_WEB_ROUTE_PREFIX

RAG_PAGE_CHAT = f"{RAG_WEB_ROUTE_PREFIX}/chat"
RAG_PAGE_SOURCES = f"{RAG_WEB_ROUTE_PREFIX}/sources"

RAG_API_CONTRACT_PREFIX = f"{RAG_API_ROUTE_PREFIX}/contract"
RAG_API_HEALTH = f"{RAG_API_CONTRACT_PREFIX}/health"
RAG_API_COLLECTIONS = f"{RAG_API_CONTRACT_PREFIX}/collections"
RAG_API_RETRIEVE = f"{RAG_API_CONTRACT_PREFIX}/retrieve"
RAG_API_HEALTH_LEGACY = f"{RAG_API_ROUTE_PREFIX}/health"
RAG_API_COLLECTIONS_LEGACY = f"{RAG_API_ROUTE_PREFIX}/collections"
RAG_API_RETRIEVE_LEGACY = f"{RAG_API_ROUTE_PREFIX}/retrieve"
RAG_API_CHAT = f"{RAG_API_ROUTE_PREFIX}/chat"
RAG_API_GITHUB_REPOS = f"{RAG_API_ROUTE_PREFIX}/github/repos"
RAG_API_DRIVE_VERIFY = f"{RAG_API_ROUTE_PREFIX}/google-drive/verify"
RAG_API_CHROMA_TEST = f"{RAG_API_ROUTE_PREFIX}/chroma/test"
