apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmctl-studio-frontend
  namespace: llmctl
spec:
  template:
    spec:
      containers:
        - name: studio-frontend
          volumeMounts:
            - name: studio-frontend-dist
              mountPath: /usr/share/nginx/html/web
      volumes:
        - name: studio-frontend-dist
          hostPath:
            path: /workspace/llmctl/app/llmctl-studio-frontend/dist
            type: DirectoryOrCreate
