from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    JSON,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from core.db import Base, BaseModel, utcnow

SCRIPT_TYPE_PRE_INIT = "pre_init"
SCRIPT_TYPE_INIT = "init"
SCRIPT_TYPE_POST_INIT = "post_init"
SCRIPT_TYPE_POST_RUN = "post_run"
_LEGACY_SKILL_SCRIPT_TYPE = "skill"
LEGACY_SKILL_SCRIPT_WRITE_ERROR = (
    "Legacy script_type=skill writes are disabled. Use first-class Skills instead."
)

SCRIPT_TYPE_CHOICES = [
    (SCRIPT_TYPE_PRE_INIT, "Pre-Init Script"),
    (SCRIPT_TYPE_INIT, "Init Script"),
    (SCRIPT_TYPE_POST_INIT, "Post-Init Script"),
    (SCRIPT_TYPE_POST_RUN, "Post-Autorun Script"),
]

SCRIPT_TYPE_LABELS = dict(SCRIPT_TYPE_CHOICES)


def is_legacy_skill_script_type(value: str | None) -> bool:
    return str(value or "").strip().lower() == _LEGACY_SKILL_SCRIPT_TYPE


def ensure_legacy_skill_script_writable(value: str | None) -> None:
    if is_legacy_skill_script_type(value):
        raise ValueError(LEGACY_SKILL_SCRIPT_WRITE_ERROR)

RUN_ACTIVE_STATUSES = ("starting", "running", "stopping")
NODE_EXECUTOR_PROVIDER_KUBERNETES = "kubernetes"
NODE_EXECUTOR_PROVIDER_CHOICES = (
    NODE_EXECUTOR_PROVIDER_KUBERNETES,
)
NODE_EXECUTOR_DISPATCH_PENDING = "dispatch_pending"
NODE_EXECUTOR_DISPATCH_SUBMITTED = "dispatch_submitted"
NODE_EXECUTOR_DISPATCH_CONFIRMED = "dispatch_confirmed"
NODE_EXECUTOR_DISPATCH_FAILED = "dispatch_failed"
NODE_EXECUTOR_DISPATCH_STATUS_CHOICES = (
    NODE_EXECUTOR_DISPATCH_PENDING,
    NODE_EXECUTOR_DISPATCH_SUBMITTED,
    NODE_EXECUTOR_DISPATCH_CONFIRMED,
    NODE_EXECUTOR_DISPATCH_FAILED,
)
NODE_EXECUTOR_FALLBACK_REASON_CHOICES = (
    "provider_unavailable",
    "preflight_failed",
    "dispatch_timeout",
    "create_failed",
    "image_pull_failed",
    "config_error",
    "unknown",
)
NODE_EXECUTOR_API_FAILURE_CATEGORY_CHOICES = (
    "socket_missing",
    "socket_unreachable",
    "api_unreachable",
    "auth_error",
    "tls_error",
    "timeout",
    "preflight_failed",
    "unknown",
)

SKILL_STATUS_DRAFT = "draft"
SKILL_STATUS_ACTIVE = "active"
SKILL_STATUS_ARCHIVED = "archived"
SKILL_STATUS_CHOICES = (
    SKILL_STATUS_DRAFT,
    SKILL_STATUS_ACTIVE,
    SKILL_STATUS_ARCHIVED,
)

FLOWCHART_NODE_TYPE_START = "start"
FLOWCHART_NODE_TYPE_END = "end"
FLOWCHART_NODE_TYPE_FLOWCHART = "flowchart"
FLOWCHART_NODE_TYPE_TASK = "task"
FLOWCHART_NODE_TYPE_PLAN = "plan"
FLOWCHART_NODE_TYPE_MILESTONE = "milestone"
FLOWCHART_NODE_TYPE_MEMORY = "memory"
FLOWCHART_NODE_TYPE_DECISION = "decision"
FLOWCHART_NODE_TYPE_RAG = "rag"
FLOWCHART_NODE_TYPE_CHOICES = (
    FLOWCHART_NODE_TYPE_START,
    FLOWCHART_NODE_TYPE_END,
    FLOWCHART_NODE_TYPE_FLOWCHART,
    FLOWCHART_NODE_TYPE_TASK,
    FLOWCHART_NODE_TYPE_PLAN,
    FLOWCHART_NODE_TYPE_MILESTONE,
    FLOWCHART_NODE_TYPE_MEMORY,
    FLOWCHART_NODE_TYPE_DECISION,
    FLOWCHART_NODE_TYPE_RAG,
)
FLOWCHART_EDGE_MODE_SOLID = "solid"
FLOWCHART_EDGE_MODE_DOTTED = "dotted"
FLOWCHART_EDGE_MODE_CHOICES = (
    FLOWCHART_EDGE_MODE_SOLID,
    FLOWCHART_EDGE_MODE_DOTTED,
)

MCP_SERVER_TYPE_CUSTOM = "custom"
MCP_SERVER_TYPE_INTEGRATED = "integrated"
MCP_SERVER_TYPE_CHOICES = (
    MCP_SERVER_TYPE_CUSTOM,
    MCP_SERVER_TYPE_INTEGRATED,
)
INTEGRATED_MCP_SERVER_KEYS = frozenset(
    {
        "llmctl-mcp",
        "github",
        "atlassian",
        "chroma",
        "google-cloud",
        "google-workspace",
    }
)
LEGACY_INTEGRATED_MCP_SERVER_KEYS = frozenset({"jira"})
SYSTEM_MANAGED_MCP_SERVER_KEYS = frozenset(
    set(INTEGRATED_MCP_SERVER_KEYS) | set(LEGACY_INTEGRATED_MCP_SERVER_KEYS)
)

MILESTONE_STATUS_PLANNED = "planned"
MILESTONE_STATUS_IN_PROGRESS = "in_progress"
MILESTONE_STATUS_AT_RISK = "at_risk"
MILESTONE_STATUS_DONE = "done"
MILESTONE_STATUS_ARCHIVED = "archived"
MILESTONE_STATUS_CHOICES = (
    MILESTONE_STATUS_PLANNED,
    MILESTONE_STATUS_IN_PROGRESS,
    MILESTONE_STATUS_AT_RISK,
    MILESTONE_STATUS_DONE,
    MILESTONE_STATUS_ARCHIVED,
)

MILESTONE_PRIORITY_LOW = "low"
MILESTONE_PRIORITY_MEDIUM = "medium"
MILESTONE_PRIORITY_HIGH = "high"
MILESTONE_PRIORITY_CHOICES = (
    MILESTONE_PRIORITY_LOW,
    MILESTONE_PRIORITY_MEDIUM,
    MILESTONE_PRIORITY_HIGH,
)

MILESTONE_HEALTH_GREEN = "green"
MILESTONE_HEALTH_YELLOW = "yellow"
MILESTONE_HEALTH_RED = "red"
MILESTONE_HEALTH_CHOICES = (
    MILESTONE_HEALTH_GREEN,
    MILESTONE_HEALTH_YELLOW,
    MILESTONE_HEALTH_RED,
)

NODE_ARTIFACT_TYPE_MEMORY = "memory"
NODE_ARTIFACT_TYPE_MILESTONE = "milestone"
NODE_ARTIFACT_TYPE_PLAN = "plan"
NODE_ARTIFACT_TYPE_DECISION = "decision"
NODE_ARTIFACT_TYPE_START = "start"
NODE_ARTIFACT_TYPE_END = "end"
NODE_ARTIFACT_TYPE_FLOWCHART = "flowchart"
NODE_ARTIFACT_TYPE_TASK = "task"
NODE_ARTIFACT_TYPE_RAG = "rag"
NODE_ARTIFACT_RETENTION_FOREVER = "forever"
NODE_ARTIFACT_RETENTION_TTL = "ttl"
NODE_ARTIFACT_RETENTION_MAX_COUNT = "max_count"
NODE_ARTIFACT_RETENTION_TTL_MAX_COUNT = "ttl_max_count"
NODE_ARTIFACT_RETENTION_CHOICES = (
    NODE_ARTIFACT_RETENTION_FOREVER,
    NODE_ARTIFACT_RETENTION_TTL,
    NODE_ARTIFACT_RETENTION_MAX_COUNT,
    NODE_ARTIFACT_RETENTION_TTL_MAX_COUNT,
)

RAG_SOURCE_KIND_LOCAL = "local"
RAG_SOURCE_KIND_GITHUB = "github"
RAG_SOURCE_KIND_GOOGLE_DRIVE = "google_drive"
RAG_SOURCE_KIND_CHOICES = (
    RAG_SOURCE_KIND_LOCAL,
    RAG_SOURCE_KIND_GITHUB,
    RAG_SOURCE_KIND_GOOGLE_DRIVE,
)

RAG_SOURCE_SCHEDULE_UNIT_MINUTES = "minutes"
RAG_SOURCE_SCHEDULE_UNIT_HOURS = "hours"
RAG_SOURCE_SCHEDULE_UNIT_DAYS = "days"
RAG_SOURCE_SCHEDULE_UNIT_WEEKS = "weeks"
RAG_SOURCE_SCHEDULE_UNIT_CHOICES = (
    RAG_SOURCE_SCHEDULE_UNIT_MINUTES,
    RAG_SOURCE_SCHEDULE_UNIT_HOURS,
    RAG_SOURCE_SCHEDULE_UNIT_DAYS,
    RAG_SOURCE_SCHEDULE_UNIT_WEEKS,
)

RAG_INDEX_MODE_FRESH = "fresh"
RAG_INDEX_MODE_DELTA = "delta"
RAG_INDEX_MODE_CHOICES = (
    RAG_INDEX_MODE_FRESH,
    RAG_INDEX_MODE_DELTA,
)

RAG_INDEX_TRIGGER_MANUAL = "manual"
RAG_INDEX_TRIGGER_SCHEDULED = "scheduled"
RAG_INDEX_TRIGGER_CHOICES = (
    RAG_INDEX_TRIGGER_MANUAL,
    RAG_INDEX_TRIGGER_SCHEDULED,
)

RAG_INDEX_JOB_KIND_INDEX = "index"
RAG_INDEX_JOB_STATUS_QUEUED = "queued"
RAG_INDEX_JOB_STATUS_RUNNING = "running"
RAG_INDEX_JOB_STATUS_PAUSING = "pausing"
RAG_INDEX_JOB_STATUS_PAUSED = "paused"
RAG_INDEX_JOB_STATUS_SUCCEEDED = "succeeded"
RAG_INDEX_JOB_STATUS_FAILED = "failed"
RAG_INDEX_JOB_STATUS_CANCELLED = "cancelled"
RAG_INDEX_JOB_STATUS_CHOICES = (
    RAG_INDEX_JOB_STATUS_QUEUED,
    RAG_INDEX_JOB_STATUS_RUNNING,
    RAG_INDEX_JOB_STATUS_PAUSING,
    RAG_INDEX_JOB_STATUS_PAUSED,
    RAG_INDEX_JOB_STATUS_SUCCEEDED,
    RAG_INDEX_JOB_STATUS_FAILED,
    RAG_INDEX_JOB_STATUS_CANCELLED,
)
RAG_INDEX_JOB_ACTIVE_STATUSES = (
    RAG_INDEX_JOB_STATUS_QUEUED,
    RAG_INDEX_JOB_STATUS_RUNNING,
    RAG_INDEX_JOB_STATUS_PAUSING,
)

CHAT_THREAD_STATUS_ACTIVE = "active"
CHAT_THREAD_STATUS_ARCHIVED = "archived"
CHAT_THREAD_STATUS_CHOICES = (
    CHAT_THREAD_STATUS_ACTIVE,
    CHAT_THREAD_STATUS_ARCHIVED,
)

CHAT_TURN_STATUS_SUCCEEDED = "succeeded"
CHAT_TURN_STATUS_FAILED = "failed"
CHAT_TURN_STATUS_CHOICES = (
    CHAT_TURN_STATUS_SUCCEEDED,
    CHAT_TURN_STATUS_FAILED,
)

