apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmctl-studio-backend
  namespace: llmctl
spec:
  template:
    spec:
      containers:
        - name: studio
          command:
            - python3
            - app/llmctl-studio-backend/run.py
          volumeMounts:
            - $patch: replace
            - name: studio-project-code
              mountPath: /app
            - name: studio-data
              mountPath: /app/data
      volumes:
        - $patch: replace
        - name: studio-project-code
          hostPath:
            path: /workspace/llmctl
            type: Directory
        - name: studio-data
          persistentVolumeClaim:
            claimName: llmctl-studio-data
