export const parityStatusLabels = {
  migrated: 'Native React',
  bridged: 'Legacy Bridge',
}

export const parityChecklist = [
  {
    wave: 'Wave 1',
    area: 'Core Shell',
    legacyPath: '/overview',
    reactPath: '/',
    status: 'migrated',
    notes: 'React shell and runtime wiring are active.',
  },
  {
    wave: 'Wave 1',
    area: 'API Diagnostics',
    legacyPath: '/api/health + /api/chat/activity',
    reactPath: '/api-diagnostics',
    status: 'migrated',
    notes: 'Connectivity checks for split frontend/backend pathing.',
  },
  {
    wave: 'Wave 1',
    area: 'Chat Activity',
    legacyPath: '/chat/activity',
    reactPath: '/chat/activity',
    status: 'migrated',
    notes: 'Reads from /api/chat/activity.',
  },
  {
    wave: 'Wave 1',
    area: 'Chat Thread Detail',
    legacyPath: '/chat',
    reactPath: '/chat/threads/:threadId',
    status: 'migrated',
    notes: 'Reads from /api/chat/threads/:threadId.',
  },
  {
    wave: 'Wave 2',
    area: 'Agents',
    legacyPath: '/agents',
    reactPath: '/agents',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 2',
    area: 'Runs',
    legacyPath: '/runs',
    reactPath: '/runs + /execution-monitor',
    status: 'bridged',
    notes: 'Run list/detail available via bridge; monitor uses native reads.',
  },
  {
    wave: 'Wave 2',
    area: 'Quick Tasks + Nodes',
    legacyPath: '/quick and /nodes',
    reactPath: '/quick, /nodes + /execution-monitor',
    status: 'bridged',
    notes: 'Quick/nodes available via bridge; node status monitor uses native reads.',
  },
  {
    wave: 'Wave 3',
    area: 'Plans',
    legacyPath: '/plans',
    reactPath: '/plans',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 3',
    area: 'Milestones',
    legacyPath: '/milestones',
    reactPath: '/milestones',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 3',
    area: 'Task Templates',
    legacyPath: '/task-templates',
    reactPath: '/task-templates',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 3',
    area: 'Memories',
    legacyPath: '/memories',
    reactPath: '/memories',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 4',
    area: 'Flowcharts',
    legacyPath: '/flowcharts',
    reactPath: '/flowcharts',
    status: 'bridged',
    notes: 'Graph/runtime/history available through bridge.',
  },
  {
    wave: 'Wave 5',
    area: 'Skills',
    legacyPath: '/skills',
    reactPath: '/skills',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 5',
    area: 'Scripts',
    legacyPath: '/scripts',
    reactPath: '/scripts',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 5',
    area: 'Attachments',
    legacyPath: '/attachments',
    reactPath: '/attachments',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 5',
    area: 'Models',
    legacyPath: '/models',
    reactPath: '/models',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 5',
    area: 'MCP Servers',
    legacyPath: '/mcps',
    reactPath: '/mcps',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 6',
    area: 'Settings Core + Provider',
    legacyPath: '/settings/core and /settings/provider',
    reactPath: '/settings/core and /settings/provider',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 6',
    area: 'Settings Runtime + Chat',
    legacyPath: '/settings/runtime and /settings/chat',
    reactPath: '/settings/runtime and /settings/chat',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 6',
    area: 'Integrations',
    legacyPath: '/settings/integrations/*',
    reactPath: '/settings/integrations/*',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 7',
    area: 'External Tools',
    legacyPath: '/github, /jira, /confluence, /chroma',
    reactPath: '/github, /jira, /confluence, /chroma',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
  {
    wave: 'Wave 7',
    area: 'RAG Pages',
    legacyPath: '/rag/chat and /rag/sources*',
    reactPath: '/rag/chat and /rag/sources*',
    status: 'bridged',
    notes: 'Served through Stage 5 legacy bridge.',
  },
]

export function buildParitySummary(items) {
  return items.reduce(
    (summary, item) => {
      const status = parityStatusLabels[item.status] ? item.status : 'bridged'
      summary.total += 1
      summary[status] = (summary[status] || 0) + 1
      return summary
    },
    {
      total: 0,
      migrated: 0,
      bridged: 0,
    },
  )
}
