export const parityStatusLabels = {
  migrated: 'Migrated',
  in_progress: 'In Progress',
  planned: 'Planned',
}

export const parityChecklist = [
  {
    wave: 'Wave 1',
    area: 'Core Shell',
    legacyPath: '/overview',
    reactPath: '/',
    status: 'migrated',
    notes: 'React shell and runtime wiring are active.',
  },
  {
    wave: 'Wave 1',
    area: 'API Diagnostics',
    legacyPath: '/api/health + /api/chat/activity',
    reactPath: '/api-diagnostics',
    status: 'migrated',
    notes: 'Connectivity checks for split frontend/backend pathing.',
  },
  {
    wave: 'Wave 1',
    area: 'Chat Activity',
    legacyPath: '/chat/activity',
    reactPath: '/chat/activity',
    status: 'migrated',
    notes: 'Reads from /api/chat/activity.',
  },
  {
    wave: 'Wave 1',
    area: 'Chat Thread Detail',
    legacyPath: '/chat',
    reactPath: '/chat/threads/:threadId',
    status: 'migrated',
    notes: 'Reads from /api/chat/threads/:threadId.',
  },
  {
    wave: 'Wave 2',
    area: 'Agents',
    legacyPath: '/agents',
    reactPath: '/agents',
    status: 'planned',
    notes: 'List/detail/edit/create workflows.',
  },
  {
    wave: 'Wave 2',
    area: 'Runs',
    legacyPath: '/runs',
    reactPath: '/runs',
    status: 'planned',
    notes: 'List/detail/edit/create + lifecycle actions.',
  },
  {
    wave: 'Wave 2',
    area: 'Quick Tasks + Nodes',
    legacyPath: '/quick and /nodes',
    reactPath: '/quick and /nodes',
    status: 'planned',
    notes: 'Queueing and status polling flows.',
  },
  {
    wave: 'Wave 3',
    area: 'Plans',
    legacyPath: '/plans',
    reactPath: '/plans',
    status: 'planned',
    notes: 'Stage/task mutation parity.',
  },
  {
    wave: 'Wave 3',
    area: 'Milestones',
    legacyPath: '/milestones',
    reactPath: '/milestones',
    status: 'planned',
    notes: 'List/detail/edit/create and state transitions.',
  },
  {
    wave: 'Wave 3',
    area: 'Task Templates',
    legacyPath: '/task-templates',
    reactPath: '/task-templates',
    status: 'planned',
    notes: 'Template CRUD + attachment management.',
  },
  {
    wave: 'Wave 3',
    area: 'Memories',
    legacyPath: '/memories',
    reactPath: '/memories',
    status: 'planned',
    notes: 'Memory CRUD and linking flows.',
  },
  {
    wave: 'Wave 4',
    area: 'Flowcharts',
    legacyPath: '/flowcharts',
    reactPath: '/flowcharts',
    status: 'planned',
    notes: 'Graph editor, execution runtime, and history.',
  },
  {
    wave: 'Wave 5',
    area: 'Skills',
    legacyPath: '/skills',
    reactPath: '/skills',
    status: 'planned',
    notes: 'CRUD/import/export and attachment handling.',
  },
  {
    wave: 'Wave 5',
    area: 'Scripts',
    legacyPath: '/scripts',
    reactPath: '/scripts',
    status: 'planned',
    notes: 'CRUD and association workflows.',
  },
  {
    wave: 'Wave 5',
    area: 'Attachments',
    legacyPath: '/attachments',
    reactPath: '/attachments',
    status: 'planned',
    notes: 'List/detail/file download lifecycle.',
  },
  {
    wave: 'Wave 5',
    area: 'Models',
    legacyPath: '/models',
    reactPath: '/models',
    status: 'planned',
    notes: 'CRUD/default selection and provider integration.',
  },
  {
    wave: 'Wave 5',
    area: 'MCP Servers',
    legacyPath: '/mcps',
    reactPath: '/mcps',
    status: 'planned',
    notes: 'CRUD and integrated/managed server behaviors.',
  },
  {
    wave: 'Wave 6',
    area: 'Settings Core + Provider',
    legacyPath: '/settings/core and /settings/provider',
    reactPath: '/settings/core and /settings/provider',
    status: 'planned',
    notes: 'Provider credentials and runtime controls.',
  },
  {
    wave: 'Wave 6',
    area: 'Settings Runtime + Chat',
    legacyPath: '/settings/runtime and /settings/chat',
    reactPath: '/settings/runtime and /settings/chat',
    status: 'planned',
    notes: 'Node executor, chat defaults, instruction controls.',
  },
  {
    wave: 'Wave 6',
    area: 'Integrations',
    legacyPath: '/settings/integrations/*',
    reactPath: '/settings/integrations/*',
    status: 'planned',
    notes: 'GitHub/Jira/Confluence/Google/HuggingFace/Chroma/RAG.',
  },
  {
    wave: 'Wave 7',
    area: 'External Tools',
    legacyPath: '/github, /jira, /confluence, /chroma',
    reactPath: '/github, /jira, /confluence, /chroma',
    status: 'planned',
    notes: 'Review and collection explorer parity.',
  },
  {
    wave: 'Wave 7',
    area: 'RAG Pages',
    legacyPath: '/rag/chat and /rag/sources*',
    reactPath: '/rag/chat and /rag/sources*',
    status: 'planned',
    notes: 'Source CRUD, quick index/delta index, and chat runtime.',
  },
]

export function buildParitySummary(items) {
  return items.reduce(
    (summary, item) => {
      const status = parityStatusLabels[item.status] ? item.status : 'planned'
      summary.total += 1
      summary[status] += 1
      return summary
    },
    {
      total: 0,
      migrated: 0,
      in_progress: 0,
      planned: 0,
    },
  )
}
