from __future__ import annotations

import os

from core.models import (
    Agent,
    AgentTask,
    Attachment,
    Flowchart,
    FlowchartEdge,
    FlowchartNode,
    FlowchartRun,
    FlowchartRunNode,
    IntegrationSetting,
    MCPServer,
    Memory,
    Milestone,
    Plan,
    PlanStage,
    PlanTask,
    Role,
    Run,
    Script,
    SCRIPT_TYPE_INIT,
    SCRIPT_TYPE_POST_INIT,
    SCRIPT_TYPE_POST_RUN,
    SCRIPT_TYPE_PRE_INIT,
    TaskTemplate,
)

# NOTE: Keep naming consistent with llmctl-studio models.
MODEL_REGISTRY = {
    "mcpserver": MCPServer,
    "mcp_server": MCPServer,
    "mcp_servers": MCPServer,
    "script": Script,
    "scripts": Script,
    "attachment": Attachment,
    "attachments": Attachment,
    "memory": Memory,
    "memories": Memory,
    "integrationsetting": IntegrationSetting,
    "integration_setting": IntegrationSetting,
    "integration_settings": IntegrationSetting,
    "agent": Agent,
    "agents": Agent,
    "autorun": Run,
    "autoruns": Run,
    "run": Run,
    "runs": Run,
    "role": Role,
    "roles": Role,
    "agenttask": AgentTask,
    "agent_task": AgentTask,
    "agent_tasks": AgentTask,
    "tasktemplate": TaskTemplate,
    "task_template": TaskTemplate,
    "task_templates": TaskTemplate,
    "flowchart": Flowchart,
    "flowcharts": Flowchart,
    "flowchartnode": FlowchartNode,
    "flowchart_node": FlowchartNode,
    "flowchart_nodes": FlowchartNode,
    "node": FlowchartNode,
    "nodes": FlowchartNode,
    "flowchartedge": FlowchartEdge,
    "flowchart_edge": FlowchartEdge,
    "flowchart_edges": FlowchartEdge,
    "flowchartrun": FlowchartRun,
    "flowchart_run": FlowchartRun,
    "flowchart_runs": FlowchartRun,
    "flowchartrunnode": FlowchartRunNode,
    "flowchart_run_node": FlowchartRunNode,
    "flowchart_run_nodes": FlowchartRunNode,
    "noderun": FlowchartRunNode,
    "node_run": FlowchartRunNode,
    "node_runs": FlowchartRunNode,
    "plan": Plan,
    "plans": Plan,
    "planstage": PlanStage,
    "plan_stage": PlanStage,
    "plan_stages": PlanStage,
    "plantask": PlanTask,
    "plan_task": PlanTask,
    "plan_tasks": PlanTask,
    "milestone": Milestone,
    "milestones": Milestone,
}

READONLY_COLUMNS = {"id", "created_at", "updated_at"}

DEFAULT_LIMIT = int(os.getenv("LLMCTL_MCP_DEFAULT_LIMIT", "200"))
MAX_LIMIT = int(os.getenv("LLMCTL_MCP_MAX_LIMIT", "1000"))

SCRIPT_TYPE_KEYS = {
    "pre_init": SCRIPT_TYPE_PRE_INIT,
    "init": SCRIPT_TYPE_INIT,
    "post_init": SCRIPT_TYPE_POST_INIT,
    "post_run": SCRIPT_TYPE_POST_RUN,
}
